name: OakCoding CI

on:
  push:
    tags:
      - submit*
      - release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        run: mvn --batch-mode clean package
      - run: mkdir -p submit && cp target/*.jar submit
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: submit

  auto-create-pr:
    if: github.repository == 'naiithink/oakcoding'
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: Package
          path: submit
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: develop
          title: Auto-build by GitHub Actions
          body: Automated build by GitHub Actions
          labels: automated pr

  deploy:
    if: github.repository == 'CS211-651/project211-oakcoding'
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: Package
          path: submit
      - name: Publish to GitHub Apache Maven Package Registry
        run: mvn --batch-mode deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/$GITHUB_REPOSITORY -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
